name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - indoor_maps
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - indoor_maps

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_SAND_0F2B10A0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "map_react" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          app_build_command: "REACT_APP_MAP_SUBSCRIPTION_KEY=aipGMyZjmHtjPnOTGTCbWQawlMoQ6MOwVLN2QFpa4fw REACT_APP_MAP_TILESET_ID=0d76d5d2-36fc-1aaa-d511-0302eb3e4bc4 REACT_APP_MAP_STATESET_ID=9587d752-caad-37a2-bd2a-a4db8afc0e70 REACT_APP_IOTC_API_KEY=SharedAccessSignature sr=3a5279fe-8817-4181-af6d-27323aa9e6d1&sig=RP1WYdta%2F8kFSHZ3pf7Cu2Gruoa07Gp2ye8rBwpYhmY%3D&skn=API&se=1665043186510 REACT_APP_IOTC_APP_SUBDOMAIN=ubsmap npm run build" # Custom build command for app content - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_SAND_0F2B10A0F }}
          action: "close"
